plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.smsimshook'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.smsimshook"
        minSdk 24
        targetSdk 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
